### ISSUE TITLE
Provide NSIS Source

### ISSUE THREAD

**Issue by ghost** [garethflowers/nodejs-portable#3]
It would be great to include the source used for compiling the launcher.

`Other/Source` exists, but sadly without the NSIS source code.

Thanks in advance!

**Comment by garethflowers** [comment]
All source code is present in the repo.

I use the [PortableApp.com Launcher](http://portableapps.com/apps/development/portableapps.com_launcher) application to generate the launcher.

**Comment by ghost** [comment]
That one I completely overlooked and didn't think of — sorry!

Thanks for the fast reply; your node launcher is the one I use over others, PowerShell and Batch scripts. :)
