### ISSUE TITLE
Please Update Node.js version.

### ISSUE THREAD

**Issue by yosbeleg89** [garethflowers/nodejs-portable#4]
Please update Node.js version to latest stable. Or if you can give a guide to do it I would do it and push that change. Thanks

**Comment by garethflowers** [comment]
This is currently being worked on and will be available soon.

**Comment by garethflowers** [comment]
[NodeJS Portable v5.3.0](https://github.com/garethflowers/nodejs-portable/releases/tag/v5.3.0) has now been released!

**Comment by yosbeleg89** [comment]
Thanks @garethflowers it is a very useful tool.
